### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jmverges** [northwoods/config#10]
Hi there,

I would like to be able to assign variables on the initialisation of Config and later be able to write values with %variableName%. I could create a parser outside but I think this could be a nice feature to have, what do you think?

Cheers

**Comment by shadowhand** [comment]
I'm not quite sure what you mean. Can you provide a more complete example?

**Comment by jmverges** [comment]
```
//config/foo.php
return [
'bar'=>'%vendorPath%/some/package/src/File.html'
]
```

and then

```

$c = \Northwoods\Config\ConfigFactory::make([
    'directory' => __DIR__.'/../config',
],[
'vendorPath' => __DIR_.'/../some-vendor-custom-path'
]);
$c->get('foo.bar') === '/var/www/mysite.dev/some-vendor-custom-path/some/package/src/File.html'
```

Something like this

**Comment by shadowhand** [comment]
@jmverges please have a look at #11 and see if it would be suitable for your needs.

**Comment by jmverges** [comment]
neat! works perfect.
